// <auto-generated />
namespace TiminsHospitalProjectV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class donationsupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(donationsupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202104240438594_donations-updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
