// <auto-generated />
namespace TiminsHospitalProjectV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IndicateForignKeyinnewsItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndicateForignKeyinnewsItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202104181405466_Indicate ForignKey in newsItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
