// <auto-generated />
namespace TiminsHospitalProjectV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateEventViewModelShow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateEventViewModelShow));
        
        string IMigrationMetadata.Id
        {
            get { return "202104191848363_updateEventViewModelShow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
